org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_version=21.1.173
neo_version_range=[21.0.0,)
loader_version_range=[4,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=butchercraft
# The human-readable display name for the mod.
mod_name=Butchercraft
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=CC-BY-NC-SA-4.0
# The mod version. See https://semver.org/
mod_version=2.6.5
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.lance5057.butchercraft
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Lance5057
# The credits of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_credits=Alan199921, Belathus, DivineAspect, FreneticScribbler, Lanse505, ParadigmOne, RoyalJelly, Skysom, unilock
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Killing an animal nets barely a few bits, maybe some meat and a few leathers, and then the rest just disappears. Such a waste!
# The URL of the mod, shown in the mods list.
mod_url=https://github.com/Lance5057/Butchercraft
# The URL of the issue tracker for the mod.
mod_issue_tracker_url=https://github.com/Lance5057/Butchercraft/issues

## Mod Dependencies

jei_version=19.21.0.246
jei_version_range=[19.0.0.0,)
emi_version=1.1.16
emi_version_range=[1.1.12,)
